batch_size: 4
multigpu: False
max_epoch: 10
adam_beta1: 0.9
adam_beta2: 0.999
learning_rate: 0.05
milestones: [2, 4, 6, 8, 10]
gamma: 0.1
checkpoint_dir: 'checkpoint'
softmax: True
network:
  name: 'DeepCov'
  input_channel: 441
  output_channel: 10