batch_size: 4
zipped: True
multigpu: False
max_epoch: 30
adam_beta1: 0.9
adam_beta2: 0.999
adam_weight_decay: 0.01
adam_eps: 0.000001
learning_rate: 0.005
milestones: [5, 10, 15, 20, 25, 30]
gamma: 0.1
checkpoint_dir: 'checkpoint'
temp_dir: 'temp'
softmax: True
network:
  name: 'SampleNet'
  input_channel: 441
  output_channel: 10