batch_size: 2
zipped: True
multigpu: True
max_epoch: 50
adam_beta1: 0.9
adam_beta2: 0.999
adam_weight_decay: 0.01
adam_eps: 0.000001
learning_rate: 0.005
milestones: [15, 25, 35, 45]
gamma: 0.2
softmax: True
checkpoint_dir: 'checkpoint'
temp_dir: 'temp'
network:
  name: 'DilatedResnet34'
  input_channel: 441
  output_channel: 10
  arch_config: [[1, 16, 16, 3, 1], [1, 16, 32, 3, 1], [3, 32, 64, 3, 1], [4, 64, 96, 3, 1],[ 6, 96, 128, 3, 2], [3, 128, 160, 3, 4]]
  