batch_size: 2
zipped: True
multigpu: True
max_epoch: 50
adam_beta1: 0.9
adam_beta2: 0.999
adam_weight_decay: 0.01
adam_eps: 0.000001
learning_rate: 0.05
milestones: [15, 25, 35, 45]
gamma: 0.2
softmax: True
checkpoint_dir: 'checkpoint'
temp_dir: 'temp'
network:
  name: 'NLResPRE'
  input_channel: 441
  output_channel: 10
  intermediate_channel: 64
  block_type: 'BasicBlock'
  blocks: 22
